/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.62
 * Generated at: 2023-02-12 12:05:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.datewise_002dreport;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.time.LocalDate;
import java.sql.*;

public final class choose_002ddate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/datewise-report/../navbar.jsp", Long.valueOf(1676203476530L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.time.LocalDate");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write(" ");

 String pa="/emp-outin-time";
 
      out.write("\r\n");
      out.write(" <head>\r\n");
      out.write("  <script src='");
      out.print(pa);
      out.write("/JS/script.js'></script>\r\n");
      out.write("  <link href='");
      out.print(pa);
      out.write("/CSS/style.css' rel='stylesheet'>\r\n");
      out.write("  <link href='");
      out.print(pa);
      out.write("/CSS/bootstrap.min.css' rel='stylesheet'>\r\n");
      out.write(" </head>\r\n");
      out.write(" <body bgcolor='cyan'>\r\n");
      out.write("   <hr style='border:2px solid teal'>\r\n");
      out.write("    <nav class='navbar navbar-expand navbar-light bg-dark'>\r\n");
      out.write("     <ul class='nav nav-pills mx-auto'>\r\n");
      out.write("      <li><a id=\"home\" class='btra' href='");
      out.print(pa);
      out.write("'>Home</a>\r\n");
      out.write("      <li><a id='add' class='btra' href='");
      out.print(pa);
      out.write("/employee/insert.jsp'>Add employee</a>\r\n");
      out.write("      <li><a id='out' class='btra' href='");
      out.print(pa);
      out.write("/outtime/employee-in-name-list.jsp'>Time Out</a>\r\n");
      out.write("      <li><a id='in' class='btra' href='");
      out.print(pa);
      out.write("/intime/employee-out-name-list.jsp'>Time In</a>\r\n");
      out.write("      <li><a id='datewise' class='btra' href='");
      out.print(pa);
      out.write("/datewise-report/choose-date.jsp'>Date wise report</a>\r\n");
      out.write("      <li><a id='empwise' class='btra' href='");
      out.print(pa);
      out.write("/employeewise-report/employee-name-list.jsp'>Employee wise report</a>\r\n");
      out.write("     </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("   <hr style='border:2px solid teal'>\r\n");
      out.write(" </body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("  ");

  LocalDate dt=LocalDate.now();
  
      out.write("\r\n");
      out.write("  <body onload=\"makeActive('datewise')\">\r\n");
      out.write("  <div class='dvv'>\r\n");
      out.write("    <label class='lahu'>View date wise report</label>\r\n");
      out.write("  </div>\r\n");
      out.write("   <table class='ta'>\r\n");
      out.write("    <tr>\r\n");
      out.write("     <td class='pd'>\r\n");
      out.write("      <form action='current-date-report.jsp' method=\"post\">\r\n");
      out.write("       <table class='cdta'>\r\n");
      out.write("        <tr>\r\n");
      out.write("         <td>Current date</td>\r\n");
      out.write("         <td align=\"right\"><button class='cdbt'>GO</button></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("       </table>\r\n");
      out.write("      </form>\r\n");
      out.write("     </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("     <td class='pd'>\r\n");
      out.write("      <form action='any-date-report.jsp' method=\"post\">\r\n");
      out.write("       <table class='cdta'>\r\n");
      out.write("        <tr>\r\n");
      out.write("         <td>Any date</td>\r\n");
      out.write("         <td><input type='date' class='tb' name='date' max=\"");
      out.print(dt);
      out.write("\" required></td>\r\n");
      out.write("         <td align=\"right\"><button class='cdbt'>GO</button></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("       </table>\r\n");
      out.write("      </form>\r\n");
      out.write("     </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("     <td class='pd'>\r\n");
      out.write("      <form action=\"date-between-report.jsp\" method=\"post\">\r\n");
      out.write("       <table class='cdta'>\r\n");
      out.write("        <tr>\r\n");
      out.write("         <td>Date between&nbsp;&nbsp;&nbsp;&nbsp;</td>\r\n");
      out.write("         <td><input type='date' class='tb' id='date1' max=\"");
      out.print(dt);
      out.write("\" name=\"date1\" required></td>\r\n");
      out.write("         <td><input type='date' class='tb' id='date2' max=\"");
      out.print(dt);
      out.write("\" name=\"date2\" required></td>\r\n");
      out.write("         <td align=\"right\"><button class='cdbt' onclick='return compareDate()'>GO</button></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("       </table>\r\n");
      out.write("      </form>\r\n");
      out.write("     </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("   </table>\r\n");
      out.write(" </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
